name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.7

      - name: Install system dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y libzbar0

      - name: Install system dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          sudo apt-get install libzbar0
        
      - name: Install system dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install zbar --version 0.10.0 -y || exit 0

      - name: Install Python dependencies
        if: runner.os == 'Linux' || runner.os == 'Windows'
        run: |
          python -m pip install --upgrade pip
          pip install qrcode pyzbar pytest pillow

      - name: Reinstall pyzbar and zbar (macOS only)
        if: runner.os == 'macOS'
        run: |
          pip install pyzbar --force-reinstall
          pip install qrcode pytest pillow

      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings
